FROM continuumio/miniconda3

LABEL maintainer="te.pickering@gmail.com"

ARG USER_ID
ARG GROUP_ID

RUN apt update && apt -y upgrade

RUN apt -y install emacs-nox procps
RUN conda update -y -n base -c defaults conda && conda update -y --all

RUN conda install -y astropy pandas seaborn matplotlib jupyterlab nodejs ipympl astroplan pymysql -c astropy

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

RUN conda clean -y --all

RUN pip install tensorflow skyfield

RUN groupadd -f -g ${GROUP_ID} halcoll && \
    useradd -l -u ${USER_ID} -g halcoll halcoll

RUN mkdir -p /home/halcoll && chown -R halcoll:halcoll /home/halcoll

EXPOSE 9999

USER halcoll

ENV HOME /home/halcoll

ENTRYPOINT ["jupyter", "lab", "--ip='*'", "--port=9999", "--no-browser"]
CMD ["--notebook-dir=/home/halcoll/halcoll/notebooks"]
