FROM conda/miniconda3

LABEL maintainer="te_pickering@gmail.com"

ARG USER_ID
ARG GROUP_ID

RUN apt update && apt -y upgrade

RUN apt -y install emacs procps

RUN conda update -y -n base -c defaults conda && conda update -y --all

RUN conda install -y tensorflow keras astropy pandas seaborn matplotlib jupyterlab nodejs ipympl

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

RUN conda clean -y --all

RUN groupadd -f -g ${GROUP_ID} halcoll && \
    useradd -l -u ${USER_ID} -g halcoll halcoll

EXPOSE 9999

RUN useradd -U -l -u 1000 -m -d /home/halcoll -s /bin/bash halcoll

USER halcoll

ENV HOME /home/halcoll

ENTRYPOINT ["jupyter", "lab", "--ip='*'", "--port=9999", "--no-browser"]
CMD ["--notebook-dir=/home/halcoll/halcoll/notebooks"]
