FROM conda/miniconda3

MAINTAINER T. E. Pickering "te_pickering@gmail.com"

RUN apt update && apt -y upgrade

RUN apt -y install emacs procps

RUN conda update -y -n base -c defaults conda && conda update -y --all

RUN conda install -y tensorflow keras astropy pandas seaborn matplotlib jupyterlab nodejs ipympl

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

RUN conda clean -y --all

EXPOSE 9999

RUN useradd -U -l -u 1000 -m -d /home/halcoll -s /bin/bash halcoll

USER 1000:1000

ADD --chown=1000:1000 ./notebooks/ /home/halcoll/notebooks
ADD --chown=1000:1000 ./halcoll/ /home/halcoll/halcoll
ADD --chown=1000:1000 ./raw_data/ /home/halcoll/raw_data

ENV HOME /home/halcoll

ENTRYPOINT ["jupyter", "lab", "--ip='*'", "--port=9999", "--no-browser"]
CMD ["--notebook-dir=/home/halcoll/notebooks"]
